version: "2.2"

services:     
  mongo-expenses:
    container_name: mongo-expenses
    image: mongodb/mongodb-community-server:latest
    ports:
      - 27017:27017
  
  typescript-expenses:
    container_name: typescript-expenses
    build: .
    env_file: 
      - .env
    ports:
     - 8080:8080
    depends_on:
     - mongo-expenses