version: "2.2"

services:     
  mongo-expenses:
    container_name: mongo-expenses
    image: mongodb/mongodb-community-server:latest
    ports:
      - 27017:27017
  
  typescript-expenses:
    container_name: typescript-expenses
    build: .
    env_file: 
      - .env
    ports:
     - 8080:8080
    depends_on:
     - mongo-expenses
  
  typescript-expenses-ui:
    container_name: typescript-expenses-ui
    build: ./client/typescript-expenses-ui
    env_file:
     - ./client/typescript-expenses-ui/.env
    ports:
     - 3000:3000
    depends_on:
      - typescript-expenses